/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class co_darma_smartmattress_analysis_healthAlgorithms_basic_DMAlgorithmMattress */

#ifndef _Included_co_darma_smartmattress_analysis_healthAlgorithms_basic_DMAlgorithmMattress
#define _Included_co_darma_smartmattress_analysis_healthAlgorithms_basic_DMAlgorithmMattress
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     co_darma_smartmattress_analysis_healthAlgorithms_basic_DMAlgorithmMattress
 * Method:    offlineStatusCalulation
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_co_darma_smartmattress_analysis_healthAlgorithms_basic_DMAlgorithmMattress_offlineStatusCalulation
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     co_darma_smartmattress_analysis_healthAlgorithms_basic_DMAlgorithmMattress
 * Method:    offlineBRCalculation
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_co_darma_smartmattress_analysis_healthAlgorithms_basic_DMAlgorithmMattress_offlineBRCalculation
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     co_darma_smartmattress_analysis_healthAlgorithms_basic_DMAlgorithmMattress
 * Method:    offlineHRCalculation
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_co_darma_smartmattress_analysis_healthAlgorithms_basic_DMAlgorithmMattress_offlineHRCalculation
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     co_darma_smartmattress_analysis_healthAlgorithms_basic_DMAlgorithmMattress
 * Method:    sleepStageAnalysis
 * Signature: ([I[I[I)[I
 */
JNIEXPORT jintArray JNICALL Java_co_darma_smartmattress_analysis_healthAlgorithms_basic_DMAlgorithmMattress_sleepStageAnalysis
  (JNIEnv *, jobject, jintArray, jintArray, jintArray);

/*
 * Class:     co_darma_smartmattress_analysis_healthAlgorithms_basic_DMAlgorithmMattress
 * Method:    offlineStatusCalForMeddo
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_co_darma_smartmattress_analysis_healthAlgorithms_basic_DMAlgorithmMattress_offlineStatusCalForMeddo
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
