ALTER TABLE `T_DEVICE` ADD INDEX `DEVICE_SERIAL_NO` (`DEVICE_SERIAL_NO`);
ALTER TABLE `T_MAN_HEALTH_MEDDO` ADD INDEX `TIME_DEVICE` (`LAST_UPDATE_TIME`,`DEVICE_ID`);
ALTER TABLE `T_MAN_BODY_MOTION_RECORD` ADD INDEX `MOTION_TIME_DEVICE` (`START_TIME`,`DEVICE_ID`);